#!/usr/bin/env ruby
p "##############################################"
p "##                                          ##"
p "##                                          ##"
p "##                                          ##"
p "##         Welcome to GitMerge              ##"
p "##                                          ##"
p "##                                          ##"
p "##                                          ##"
p "##############################################"
p Time.now
branches = [
  "5.3.4.05",
  "5.3.5.02",
  "5.3.5.03",
  "5.3.5.04",
  "5.3.6",
  "5.3.6.01",
  "5.3.7",
  "5.3.7.01",
  "5.3.7.02",
]
class Branch
  attr_accessor :name
  def initialize(name)
    @name = name
  end


  def parse(input)
    if input


    end
  end

  def validate(input)
    unless input.include?(".")

    end
  end
end


